kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-sli-config-sockshop
  namespace: keptn
data:
  custom-queries: |
    cpu_usage: avg(rate(container_cpu_usage_seconds_total{namespace="$PROJECT-$STAGE",pod_name=~"$SERVICE-primary-.*"}[5m]))
