---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sli-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: prometheus-sli-service
  replicas: 1
  template:
    metadata:
      labels:
        run: prometheus-sli-service
    spec:
      containers:
      - name: prometheus-sli-service
        image: keptncontrib/prometheus-sli-service:0.2.2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: CONFIGURATION_SERVICE
          value: 'http://configuration-service:8080'
        - name: EVENTBROKER
          value: 'http://event-broker/keptn'
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-sli-service
  namespace: keptn
  labels:
    run: prometheus-sli-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: prometheus-sli-service
---
## prometheus-sli-service sh.keptn.internal.event.get-sli-distributor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sli-service-monitoring-configure-distributor
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: distributor
  replicas: 1
  template:
    metadata:
      labels:
        run: distributor
    spec:
      containers:
      - name: distributor
        image: keptn/distributor:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PUBSUB_URL
          value: 'nats://keptn-nats-cluster'
        - name: PUBSUB_TOPIC
          value: 'sh.keptn.internal.event.get-sli'
        - name: PUBSUB_RECIPIENT
          value: 'prometheus-sli-service'
