---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: prometheus-service
  replicas: 1
  template:
    metadata:
      labels:
        run: prometheus-service
    spec:
      containers:
      - name: prometheus-service
        image: keptn/prometheus-sli-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: CONFIGURATION_SERVICE
          value: 'http://configuration-service.keptn.svc.cluster.local:8080'
        - name: EVENTBROKER
          value: 'http://event-broker.keptn.svc.cluster.local/keptn'
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: keptn
  labels:
    run: prometheus-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: prometheus-service
